require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Max: 130
  IgnoredPatterns:
      - '\s+# rubocop'
      - '^\s*#'
      - '^\s*it .*, except: \{.*\} do$'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: false

Metrics/AbcSize:
  Max: 27
  Exclude:
    - 'lib/automationagent/webdriver/remote/http/curb.rb'
    - 'lib/automationagent/webdriver/support/color.rb'

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - 'automationagent-webdriver.gemspec'

Metrics/ClassLength:
  CountComments: false
  Max: 160
  Exclude:
    - 'lib/automationagent/webdriver/remote/bridge.rb'
    - 'lib/automationagent/webdriver/remote/capabilities.rb'

Metrics/CyclomaticComplexity:
  Max: 9
  Exclude:
    - 'lib/automationagent/webdriver/remote/capabilities.rb'

Metrics/MethodLength:
  CountComments: false
  Max: 22
  Exclude:
    - 'lib/automationagent/server.rb'
    - 'lib/automationagent/webdriver/common/driver.rb'
    - 'lib/automationagent/webdriver/remote/http/default.rb'

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - 'lib/automationagent/webdriver/common/platform.rb'
    - 'spec/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false

# TODO: Refactor Chrome::Bridge#create_capabilities
Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'lib/automationagent/webdriver/remote/capabilities.rb'

Naming/FileName:
  Exclude:
    - 'lib/automationagent-webdriver.rb'

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - ex
    - by
    - id
    - io

RSpec/AnyInstance:
  Enabled: false

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/unit/automationagent/webdriver/socket_poller_spec.rb'

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - 'spec/unit/automationagent/webdriver/socket_poller_spec.rb'

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/CommentedKeyword:
  Enabled: false

Style/Dir:
  Exclude:
    - 'automationagent-webdriver.gemspec'

# Consider documenting all top-level classes and modules
Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Port Integers do not need underscores
Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/SlicingWithRange:
  Enabled: true

Style/StringLiterals:
  Enabled: false
